name: Update RapidJSON

on:
    schedule:
        - cron: "0 0 1 * *" # Runs every month
    workflow_dispatch:

jobs:
    download-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install GitHub CLI
              run: sudo apt-get install -y gh

            - name: Download RapidJSON source code
              run: |
                  wget https://github.com/Tencent/rapidjson/archive/refs/heads/master.tar.gz -O rapidjson.tar.gz
                  mkdir rapidjson-latest
                  tar -xzf rapidjson.tar.gz --strip-components=1 -C rapidjson-latest
                  tar -czf rapidjson.tar.gz rapidjson-latest

            - name: Delete previous release (if exists)
              run: |
                  gh release delete rapidjson-latest --yes || true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Release
              run: |
                  gh release create rapidjson-latest rapidjson.tar.gz --title "RapidJSON Latest" --notes "Automated monthly update"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
